import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Inlines the package version into src/version.ts so the client can stamp it
// into the User-Agent header. tsc builds this package with `rootDir: ./src`,
// so importing package.json directly from src is not possible; we generate a
// source constant instead. Runs as part of `build`.
const here = dirname(fileURLToPath(import.meta.url));
const { version } = JSON.parse(
  readFileSync(resolve(here, "../package.json"), "utf8"),
);

const contents = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit by hand.
// Regenerated from package.json on every build.
export const VERSION = ${JSON.stringify(version)};
`;

writeFileSync(resolve(here, "../src/version.ts"), contents);
