export {
  AgentFeature,
  AgentFeedbackOutcome,
  AgentFeedbackResponse,
  AgentWhoamiResponse,
  AgentProjectListItem,
  AgentCurrentProjectResponse,
  AgentSetProjectResponse,
  getAgentWhoami,
  getAgentProjects,
  getAgentCurrentProject,
  setAgentCurrentProject,
  StructuredSessionDataResponse,
  StructuredSessionSummary,
  DiffsSummaryOptions,
  DiffsSummaryScreenshot,
  DiffsSummaryReplayDiff,
  DiffsSummaryDiff,
  DiffsSummaryResponse,
  DiffsSummaryCountsResponse,
  DiffDecisionState,
  AgentDiffComment,
  AgentDiffCommentReply,
  AgentApproveDiffResponse,
  AgentDiffCommentMutationResponse,
  AgentDiffCommentCoordinates,
  ScreenshotDomDiffResponse,
  ScreenshotUrlsResponse,
  CompactRange,
  FileWithCompactRanges,
  TestRunForCommitResponse,
  TestRunCheckType,
  TestRunCheckReport,
  TestRunCheckReportResponse,
  TestRunJsCoverageResponse,
  TestRunJsCoverageOptions,
  TestRunJsCoverageResponseV2,
  TestRunCoverageFile,
  shouldDefaultToExecutedRanges,
  COVERAGE_ORDER_BY_FIELDS,
  CoverageOrderByField,
  SESSIONS_ORDER_BY_FIELDS,
  SessionsOrderByField,
  SELECTED_SINCE_UNKNOWN_REASONS,
  SelectedSinceUnknown,
  ProjectJsCoverageOptions,
  ProjectJsCoverageResponse,
  TestRunJsCoverageSummaryResponse,
  ProjectJsCoverageSummaryResponse,
  ReplayJsCoverageResponse,
  CoverageFileDiff,
  CoverageDiffDelta,
  ReplayDiffJsCoverageDiffResponse,
  TestRunJsCoverageDiffResponse,
  TestRunJsCoverageDiffOptions,
  TestRunProcessingResponse,
  isTestRunProcessingResponse,
  DIFFS_SUMMARY_COUNTS_CLIENT_VERSION,
  REPLAY_JS_COVERAGE_CLIENT_VERSION,
  REPLAY_DIFF_JS_COVERAGE_DIFF_CLIENT_VERSION,
  TESTRUN_COVERAGE_AGGREGATE_CLIENT_VERSION,
  getTestRunJsCoverageDiff,
  TimelineDiffEntry,
  TimelineDiffResponse,
  getStructuredSessionData,
  getTestRunDiffsSummary,
  getTestRunDiffsSummaryCounts,
  DIFFS_SUMMARY_CLIENT_VERSION,
  getDiffComments,
  createDiffComment,
  replyToDiffComment,
  rejectDiff,
  approveDiff,
  ignoreDiff,
  getScreenshotDomDiff,
  getTestRunForCommit,
  getTestRunForPullRequest,
  completeBaseRun,
  CompleteBaseRunResponse,
  promoteSessions,
  PromoteSessionsResponse,
  getTestRunCheckReport,
  getTestRunCheckAvailableIds,
  TestRunCheckAvailableId,
  getTestRunJsCoverage,
  getProjectJsCoverage,
  getTestRunJsCoverageSummary,
  getProjectJsCoverageSummary,
  getReplayJsCoverage,
  getReplayDiffJsCoverage,
  getScreenshotUrls,
  getTimelineDiff,
  getSessions,
  SessionsResponse,
  SessionListItem,
  SessionStatus,
  SessionAbandonmentReason,
  SessionSource,
  submitAgentFeedback,
  trackAgentFeatureUsage,
} from "./api/agent.api";
export {
  getTestRunStats,
  getProjectDailyStats,
  getTestRunEventStats,
  type BulkStatsPagination,
  type TestRunStatsApprover,
  type TestRunStatsItem,
  type TestRunStatsResponse,
  type TestRunStatsOptions,
  type TestRunEventType,
  type TestRunEventActor,
  type TestRunEventStatsItem,
  type TestRunEventStatsPagination,
  type TestRunEventStatsResponse,
  type TestRunEventStatsOptions,
  type ProjectDailyRunTimeStats,
  type ProjectDailyPrStats,
  type PrNumbersByBugPreventionCategory,
  type ProjectDailyStatsItem,
  type ProjectDailyStatsResponse,
  type ProjectDailyStatsOptions,
} from "./api/agent-stats.api";
export {
  type AgentCheckComment,
  type AgentCheckReviewResponse,
  type AgentCheckTarget,
  approveCheck,
  getCheckComments,
  ignoreCheck,
  rejectCheck,
} from "./api/agent-check-reviews.api";
export { getTestRuns } from "./api/agent-test-runs.api";
export type {
  GetTestRunsOptions,
  TestRunListItem,
  TestRunsResponse,
} from "./api/agent-test-runs.types";
export * from "./api/github-cloud-replay.api";
export {
  WhoamiOrganization,
  WhoamiResponse,
  getWhoami,
  OAuthProject,
  OAuthProjectsResponse,
  getOAuthProjects,
  OAuthDefaultProjectResponse,
  getOAuthDefaultProject,
  setOAuthDefaultProject,
  clearOAuthDefaultProject,
} from "./api/oauth.api";
export {
  GetRepoUrlOptions,
  RepoUrlResponse,
  getProject,
  getRepoUrl,
  GetSourceArchiveUrlOptions,
  SourceArchiveUrlResponse,
  getSourceArchiveUrl,
  RequestSourceCodeUploadUrlParams,
  RequestSourceCodeUploadUrlResponse,
  requestSourceCodeUploadUrl,
} from "./api/project.api";
export { CrawlerTestRun, createCrawlerTestRun } from "./api/crawler.api";
export {
  ReplayV3UploadLocations,
  GetReplayV3DownloadUrlsOptions,
  getReplay,
  getReplayDownloadUrl,
  getReplayV3DownloadUrls,
} from "./api/replay.api";
export {
  getRecordedSession,
  getRecordedSessionData,
  getBackendReplayEnv,
  BackendReplayEnvVariable,
  getRecordingCommandId,
  postSessionIdNotification,
} from "./api/session.api";
export { ReplayDiffResponse, getReplayDiff } from "./api/replay-diff.api";
export {
  getPrDescriptionForTestRun,
  getPrDiff,
  getPrDiffForTestRun,
} from "./api/source-code.api";
export {
  ExecuteSecureTunnelTestRunOptions,
  executeSecureTunnelTestRun,
  getTestRun,
  getTestRunNetworkPatchingResult,
  markTestRunExpectsCustomChecks,
  getTestRunData,
  getTestRunReplayDiffs,
  GetLatestTestRunOptions,
  getLatestTestRunResults,
  SearchTestRunsOptions,
  searchTestRuns,
  TestRun,
  emitTelemetry,
} from "./api/test-run.api";
export { GetIsLockedOptions, getIsLocked } from "./api/deployment-lock.api";
export {
  COMMIT_LABEL_TYPES,
  CommitLabelType,
  labelCommit,
  LabelCommitResponse,
} from "./api/commit-label.api";
export { IN_PROGRESS_TEST_RUN_STATUS } from "./api/test-run.constants";
export {
  IGNORE_DIFF_CRITERIA,
  MAX_AGENT_DIFF_COMMENT_TEXT_LENGTH,
  REPORT_FLAKE_DESCRIPTION,
} from "./api/agent.constants";
export { TEST_RUN_STATUS_CLIENT_VERSION } from "./api/test-run-status-client-version";
export {
  getApiToken,
  getAuthToken,
  readFileBasedToken,
} from "./api-token.utils";
export {
  ClientOptions,
  createClient,
  createClientWithOAuth,
  declareClientAppInfo,
  isInteractiveContext,
  makeRequest,
  resolveApiTokenWithOAuth,
} from "./client";
export {
  CLI_LOGIN_INTENT_ONBOARD,
  performOAuthLogin,
} from "./oauth/oauth-login";
export { performDeviceLogin } from "./oauth/oauth-device-login";
export { getValidAccessToken } from "./oauth/oauth-refresh";
export {
  type OAuthRevocationResult,
  revokeOAuthRefreshToken,
} from "./oauth/oauth-revoke";
export {
  clearOAuthTokens,
  getStoredOAuthTokens,
} from "./oauth/oauth-token-store";
export { resolveDefaultProjectId } from "./oauth/default-project";
export { getWebappBaseUrl } from "./oauth/oauth-constants";
export { migrateLegacySelectedProjectIfPresent } from "./oauth/legacy-project-migration";
export { getJwtClaims, isJwtExpired, isOAuthJwt } from "./oauth/oauth-utils";
export type {
  MeticulousClient,
  Response,
  RequestConfig,
} from "./types/client.types";
export { getProxyAgent } from "./utils/get-proxy-agent";
export { isOpaqueId, assertOpaqueId } from "./utils/opaque-id";
export {
  PutFileToSignedUrlOptions,
  putFileToSignedUrl,
} from "./utils/put-file-to-signed-url";
export {
  UploadError,
  isTransientUploadError,
  retryTransientUploadErrors,
  RetryTransientUploadErrorsOptions,
} from "./utils/retry-transient-upload-errors";
export {
  ProjectIdentifier,
  AgentProjectOverride,
  RequestAssetUploadParams,
  RequestAssetUploadResponse,
  requestAssetUpload,
  requestMultipartAssetUpload,
  RequestMultipartAssetUploadResponse,
  RequestUploadPartParams,
  RequestUploadPartResponse,
  requestUploadPart,
  RequestGitDiffUploadParams,
  RequestGitDiffUploadResponse,
  requestGitDiffUpload,
  RequestDeploymentSourceMapArtifactUploadParams,
  RequestDeploymentSourceMapArtifactUploadResponse,
  requestDeploymentSourceMapArtifactUpload,
  ChunkPathOverlap,
  CompleteAssetUploadParams,
  CompleteAssetUploadResponse,
  completeAssetUpload,
  CompleteContainerUploadParams,
  CompleteContainerUploadResponse,
  completeContainerUpload,
  MultiPartUploadInfo,
  ProjectAssetChunkReference,
  RequestedProjectAssetChunkReference,
  ProjectAssetChunkVersionLookup,
  CreateRunWithUploadedAssetChunksParams,
  CreateRunWithUploadedAssetChunksResponse,
  createRunWithUploadedAssetChunks,
  TriggerRunWithUploadedAssetChunksParams,
  triggerRunWithUploadedAssetChunks,
  RequestAssetChunkUploadParams,
  RequestAssetChunkUploadResponse,
  requestAssetChunkUpload,
  CompleteAssetChunkUploadParams,
  CompleteAssetChunkUploadResponse,
  completeAssetChunkUpload,
  downloadProjectDeployment,
  GetContainerDeploymentResponse,
  getContainerDeployment,
  ContainerEnvVariable,
  ProjectDeploymentSource,
  AgentUploadBuildResponse,
  AgentUploadAssetBuildParams,
  agentUploadAssetBuild,
  AgentUploadContainerBuildParams,
  agentUploadContainerBuild,
  AgentUploadGitDiffBuildParams,
  AgentUploadGitDiffBuildResponse,
  agentUploadGitDiffBuild,
  AgentTriggerTestRunParams,
  AgentTriggerTestRunResponse,
  agentTriggerTestRun,
  TriggerDeploymentSourceMapIngestionParams,
  TriggerDeploymentSourceMapIngestionResponse,
  triggerDeploymentSourceMapIngestion,
  GetDeploymentSourceMapMappingArtifactParams,
  GetDeploymentSourceMapMappingArtifactResponse,
  getDeploymentSourceMapMappingArtifact,
  GetDeploymentSourceMapArtifactDownloadUrlParams,
  GetDeploymentSourceMapArtifactDownloadUrlResponse,
  getDeploymentSourceMapArtifactDownloadUrl,
} from "./api/project-deployments.api";
export {
  RequestAgenticInstructionsUploadParams,
  RequestAgenticInstructionsUploadResponse,
  requestAgenticInstructionsUpload,
  CompleteAgenticSessionGenerationParams,
  CompleteAgenticSessionGenerationResponse,
  AgenticAppTarget,
  AgenticAssetsAppTarget,
  AgenticAssetsBackend,
  AgenticContainerAppTarget,
  completeAgenticSessionGeneration,
  AgenticRunResultCaseOutcome,
  AgenticRunResultCaseTag,
  AGENTIC_RUN_NOT_TESTABLE_CATEGORIES,
  AgenticRunNotTestableCategory,
  AgenticRunNotTestable,
  AgenticRunMockDataProvenance,
  AgenticRunCaseCheckVerdict,
  AgenticRunCaseCheckCitation,
  AgenticRunCaseCheckEvidence,
  AgenticRunCaseCheckFixChange,
  AgenticRunCaseCheck,
  AgenticRunResultCase,
  AgenticRunComparisonVerdict,
  AgenticRunComparisonStatus,
  AgenticRunComparisonDisplay,
  AgenticRunComparisonSide,
  AgenticRunScreenshotComparison,
  AgenticCaseProvenance,
  AgenticRunSummary,
  AgenticRunSummaryTakeaway,
  AgenticRunFeaturedFlowMedia,
  AgenticRunResultStep,
  AgenticRunPlaybackAction,
  AgenticRunHighlightRegion,
  AgenticRunUrlHighlightRange,
  AgenticRunStepKind,
  AgenticRunStepOutcome,
  AgenticRunMetadata,
  AgenticRunModelUsage,
  AgenticRunTraceEventKind,
  AgenticRunTraceEvent,
  AgenticRunTraceUsage,
  AgenticRunTrace,
  AgenticRunCaseTrace,
  AgenticRunTraces,
  AgenticRunCoverage,
  AgenticRunCoverageFile,
  AgenticRunResultBlob,
  AgenticResultArtifactKind,
  ReportAgenticRunResultResponse,
  RequestAgenticResultUploadParams,
  RequestAgenticResultUploadResponse,
  requestAgenticResultUpload,
  CompleteAgenticRunResultParams,
  completeAgenticRunResult,
  ReportAgenticRunFailureParams,
  reportAgenticRunFailure,
  AgenticArtifactUploadFile,
  RequestAgenticArtifactUploadsParams,
  RequestAgenticArtifactUploadsResponse,
  requestAgenticArtifactUploads,
  RequestAgenticTestcasesUploadParams,
  RequestAgenticTestcasesUploadResponse,
  requestAgenticTestcasesUpload,
  GetAgenticRunCoverageParams,
  GetAgenticRunCoverageResponse,
  getAgenticRunCoverage,
  IsAgenticRunCancelledParams,
  IsAgenticRunCancelledResponse,
  isAgenticRunCancelled,
  ReserveAgenticTotpSlotParams,
  ReserveAgenticTotpSlotResponse,
  reserveAgenticTotpSlot,
  CancelAgenticTotpSlotWaitParams,
  cancelAgenticTotpSlotWait,
  SearchRecordedRequestsParams,
  SearchRecordedRequestsResponse,
  RecordedRequestDetails,
  RecordedRequestMatch,
  searchRecordedRequests,
  GetRecordedRequestParams,
  GetRecordedRequestResponse,
  RecordedRequestDocument,
  getRecordedRequest,
  AgenticRunProgressCase,
  AgenticRunProgressCaseStatus,
  AgenticRunProgressSnapshot,
  AgentSwarmMemoryCandidate,
  AgentSwarmMemoryCandidateAudience,
  AgentSwarmMemoryCandidateCategory,
  RequestAgenticProgressUploadParams,
  RequestAgenticProgressUploadResponse,
  requestAgenticProgressUpload,
} from "./api/agentic-session-generation.api";
export {
  CatalogMaintenanceWorkflowStatusResponse,
  GetCatalogMaintenanceWorkflowStatusParams,
  LaunchCatalogMaintenanceParams,
  LaunchCatalogMaintenanceResponse,
  RequestCatalogMaintenanceProposalUploadParams,
  RequestCatalogMaintenanceProposalUploadResponse,
  getCatalogMaintenanceWorkflowStatus,
  launchCatalogMaintenance,
  requestCatalogMaintenanceProposalUpload,
} from "./api/catalog-maintenance.api";
export { GetRegistryAuthResponse, getRegistryAuth } from "./api/registry.api";
export {
  isAuthFailureStatus,
  isFetchError,
  maybeEnrichFetchError,
  maybeEnrichMissingAuthFetchError,
  MISSING_AUTH_GUIDANCE,
} from "./errors";
export {
  EditedFileWithLines,
  GetRelevantSessionsParams,
  GetRelevantSessionsResponse,
  RelevantSession,
  getRelevantSessions,
} from "./api/local-changes.api";
/**
 * @deprecated Prefer importing `TestRunDataLocations` from `@alwaysmeticulous/api` instead of `@alwaysmeticulous/client`.
 */
export { TestRunDataLocations } from "@alwaysmeticulous/api";
