export {
  AgentFeature,
  AgentFeedbackOutcome,
  AgentFeedbackResponse,
  StructuredSessionDataResponse,
  StructuredSessionSummary,
  DiffsSummaryOptions,
  DiffsSummaryScreenshot,
  DiffsSummaryReplayDiff,
  DiffsSummaryResponse,
  DiffsSummaryCountsResponse,
  DiffDecisionState,
  ScreenshotDomDiffResponse,
  ScreenshotUrlsResponse,
  CompactRange,
  FileWithCompactRanges,
  TestRunForCommitResponse,
  TestRunJsCoverageResponse,
  TestRunJsCoverageOptions,
  TestRunJsCoverageResponseV2,
  TestRunCoverageFile,
  shouldDefaultToExecutedRanges,
  ProjectJsCoverageOptions,
  ProjectJsCoverageResponse,
  ReplayJsCoverageResponse,
  CoverageFileDiff,
  ReplayDiffJsCoverageDiffResponse,
  TimelineDiffEntry,
  TimelineDiffResponse,
  getStructuredSessionData,
  getTestRunDiffsSummary,
  getTestRunDiffsSummaryCounts,
  getScreenshotDomDiff,
  getTestRunForCommit,
  getTestRunJsCoverage,
  getProjectJsCoverage,
  getReplayJsCoverage,
  getReplayDiffJsCoverage,
  getScreenshotUrls,
  getTimelineDiff,
  getSessions,
  SessionsResponse,
  SessionListItem,
  SessionStatus,
  SessionAbandonmentReason,
  submitAgentFeedback,
  trackAgentFeatureUsage,
} from "./api/agent.api";
export * from "./api/github-cloud-replay.api";
export {
  WhoamiOrganization,
  WhoamiResponse,
  getWhoami,
  OAuthProject,
  OAuthProjectsResponse,
  getOAuthProjects,
  OAuthDefaultProjectResponse,
  getOAuthDefaultProject,
  setOAuthDefaultProject,
  clearOAuthDefaultProject,
} from "./api/oauth.api";
export {
  GetRepoUrlOptions,
  RepoUrlResponse,
  getProject,
  getRepoUrl,
  GetSourceArchiveUrlOptions,
  SourceArchiveUrlResponse,
  getSourceArchiveUrl,
  RequestSourceCodeUploadUrlParams,
  RequestSourceCodeUploadUrlResponse,
  requestSourceCodeUploadUrl,
} from "./api/project.api";
export { CrawlerTestRun, createCrawlerTestRun } from "./api/crawler.api";
export {
  ReplayV3UploadLocations,
  GetReplayV3DownloadUrlsOptions,
  getReplay,
  getReplayDownloadUrl,
  getReplayV3DownloadUrls,
} from "./api/replay.api";
export {
  getRecordedSession,
  getRecordedSessionData,
  getBackendReplayEnv,
  BackendReplayEnvVariable,
  getRecordingCommandId,
  postSessionIdNotification,
} from "./api/session.api";
export { ReplayDiffResponse, getReplayDiff } from "./api/replay-diff.api";
export {
  getPrDescriptionForTestRun,
  getPrDiff,
  getPrDiffForTestRun,
} from "./api/source-code.api";
export {
  ExecuteSecureTunnelTestRunOptions,
  executeSecureTunnelTestRun,
  getTestRun,
  getTestRunNetworkPatchingResult,
  markTestRunExpectsCustomChecks,
  getTestRunData,
  getTestRunReplayDiffs,
  GetLatestTestRunOptions,
  getLatestTestRunResults,
  TestRun,
  emitTelemetry,
} from "./api/test-run.api";
export { GetIsLockedOptions, getIsLocked } from "./api/deployment-lock.api";
export {
  COMMIT_LABEL_TYPES,
  CommitLabelType,
  labelCommit,
  LabelCommitResponse,
} from "./api/commit-label.api";
export { IN_PROGRESS_TEST_RUN_STATUS } from "./api/test-run.constants";
export {
  getApiToken,
  getAuthToken,
  readFileBasedToken,
} from "./api-token.utils";
export {
  ClientOptions,
  createClient,
  createClientWithOAuth,
  declareClientAppInfo,
  isInteractiveContext,
  makeRequest,
  resolveApiTokenWithOAuth,
} from "./client";
export { performOAuthLogin } from "./oauth/oauth-login";
export { performDeviceLogin } from "./oauth/oauth-device-login";
export { getValidAccessToken } from "./oauth/oauth-refresh";
export {
  clearOAuthTokens,
  getStoredOAuthTokens,
} from "./oauth/oauth-token-store";
export { resolveDefaultProjectId } from "./oauth/default-project";
export { migrateLegacySelectedProjectIfPresent } from "./oauth/legacy-project-migration";
export { getJwtClaims, isJwtExpired, isOAuthJwt } from "./oauth/oauth-utils";
export type { MeticulousClient } from "./types/client.types";
export { getProxyAgent } from "./utils/get-proxy-agent";
export {
  PutFileToSignedUrlOptions,
  putFileToSignedUrl,
} from "./utils/put-file-to-signed-url";
export {
  UploadError,
  isTransientUploadError,
  retryTransientUploadErrors,
  RetryTransientUploadErrorsOptions,
} from "./utils/retry-transient-upload-errors";
export {
  ProjectIdentifier,
  AgentProjectOverride,
  RequestAssetUploadParams,
  RequestAssetUploadResponse,
  requestAssetUpload,
  requestMultipartAssetUpload,
  RequestMultipartAssetUploadResponse,
  RequestUploadPartParams,
  RequestUploadPartResponse,
  requestUploadPart,
  RequestGitDiffUploadParams,
  RequestGitDiffUploadResponse,
  requestGitDiffUpload,
  ChunkPathOverlap,
  CompleteAssetUploadParams,
  CompleteAssetUploadResponse,
  completeAssetUpload,
  CompleteContainerUploadParams,
  CompleteContainerUploadResponse,
  completeContainerUpload,
  MultiPartUploadInfo,
  ProjectAssetChunkReference,
  RequestedProjectAssetChunkReference,
  ProjectAssetChunkVersionLookup,
  CreateRunWithUploadedAssetChunksParams,
  CreateRunWithUploadedAssetChunksResponse,
  createRunWithUploadedAssetChunks,
  TriggerRunWithUploadedAssetChunksParams,
  triggerRunWithUploadedAssetChunks,
  RequestAssetChunkUploadParams,
  RequestAssetChunkUploadResponse,
  requestAssetChunkUpload,
  CompleteAssetChunkUploadParams,
  CompleteAssetChunkUploadResponse,
  completeAssetChunkUpload,
  downloadProjectDeployment,
  GetContainerDeploymentResponse,
  getContainerDeployment,
  ContainerEnvVariable,
  ProjectDeploymentSource,
  AgentUploadBuildResponse,
  AgentUploadAssetBuildParams,
  agentUploadAssetBuild,
  AgentUploadContainerBuildParams,
  agentUploadContainerBuild,
  AgentUploadGitDiffBuildParams,
  AgentUploadGitDiffBuildResponse,
  agentUploadGitDiffBuild,
  AgentTriggerTestRunParams,
  AgentTriggerTestRunResponse,
  agentTriggerTestRun,
} from "./api/project-deployments.api";
export {
  RequestAgenticInstructionsUploadParams,
  RequestAgenticInstructionsUploadResponse,
  requestAgenticInstructionsUpload,
  CompleteAgenticSessionGenerationParams,
  CompleteAgenticSessionGenerationResponse,
  AgenticAppTarget,
  AgenticAssetsAppTarget,
  AgenticAssetsBackend,
  AgenticContainerAppTarget,
  completeAgenticSessionGeneration,
  AgenticRunResultCaseOutcome,
  AgenticRunResultCaseTag,
  AgenticRunResultCase,
  AgenticRunResultStep,
  AgenticRunStepKind,
  AgenticRunMetadata,
  AgenticRunTraceEventKind,
  AgenticRunTraceEvent,
  AgenticRunTraceUsage,
  AgenticRunTrace,
  AgenticRunCaseTrace,
  AgenticRunTraces,
  AgenticRunCoverage,
  AgenticRunCoverageFile,
  ReportAgenticRunResultParams,
  ReportAgenticRunResultResponse,
  reportAgenticRunResult,
  AgenticArtifactUploadFile,
  RequestAgenticArtifactUploadsParams,
  RequestAgenticArtifactUploadsResponse,
  requestAgenticArtifactUploads,
  GetAgenticRunCoverageParams,
  GetAgenticRunCoverageResponse,
  getAgenticRunCoverage,
  GetAgenticChangedFilesParams,
  GetAgenticChangedFilesResponse,
  AgenticChangedFile,
  getAgenticChangedFiles,
  GetAgenticRepoFileParams,
  GetAgenticRepoFileResponse,
  getAgenticRepoFile,
  SearchAgenticRepoCodeParams,
  SearchAgenticRepoCodeResponse,
  AgenticRepoSearchMatch,
  searchAgenticRepoCode,
  GetAgenticFileChangesParams,
  GetAgenticFileChangesResponse,
  getAgenticFileChanges,
  ListAgenticRepoTreeParams,
  ListAgenticRepoTreeResponse,
  AgenticRepoTreeEntry,
  listAgenticRepoTree,
  AgenticRepoLeaseRef,
  AcquireAgenticRepoLeaseParams,
  AcquireAgenticRepoLeaseResponse,
  acquireAgenticRepoLease,
  GetAgenticRepoLeaseStatusParams,
  AgenticRepoLeaseStatusResponse,
  getAgenticRepoLeaseStatus,
  HeartbeatAgenticRepoLeaseParams,
  HeartbeatAgenticRepoLeaseResponse,
  heartbeatAgenticRepoLease,
  ReleaseAgenticRepoLeaseParams,
  ReleaseAgenticRepoLeaseResponse,
  releaseAgenticRepoLease,
  IsAgenticRunCancelledParams,
  IsAgenticRunCancelledResponse,
  isAgenticRunCancelled,
} from "./api/agentic-session-generation.api";
export {
  getDiscoveryRepoFile,
  searchDiscoveryRepoCode,
  listDiscoveryRepoTree,
  acquireDiscoveryRepoLease,
  getDiscoveryRepoLeaseStatus,
  heartbeatDiscoveryRepoLease,
  releaseDiscoveryRepoLease,
} from "./api/session-transform-discovery.api";
export {
  CatalogMaintenanceWorkflowStatusResponse,
  GetCatalogMaintenanceWorkflowStatusParams,
  LaunchCatalogMaintenanceParams,
  LaunchCatalogMaintenanceResponse,
  RequestCatalogMaintenanceProposalUploadParams,
  RequestCatalogMaintenanceProposalUploadResponse,
  getCatalogMaintenanceWorkflowStatus,
  launchCatalogMaintenance,
  requestCatalogMaintenanceProposalUpload,
} from "./api/catalog-maintenance.api";
export { GetRegistryAuthResponse, getRegistryAuth } from "./api/registry.api";
export {
  isAuthFailureStatus,
  isFetchError,
  maybeEnrichFetchError,
  maybeEnrichMissingAuthFetchError,
  MISSING_AUTH_GUIDANCE,
} from "./errors";
export {
  EditedFileWithLines,
  GetRelevantSessionsParams,
  GetRelevantSessionsResponse,
  RelevantSession,
  getRelevantSessions,
} from "./api/local-changes.api";
/**
 * @deprecated Prefer importing `TestRunDataLocations` from `@alwaysmeticulous/api` instead of `@alwaysmeticulous/client`.
 */
export { TestRunDataLocations } from "@alwaysmeticulous/api";
